AppBundle\Entity\ProductCategory:
    type: entity
    table: product_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        category_id: { type: integer }
        product_id: { type: integer }
    manyToOne:
      product:
        targetEntity: Product
        inversedBy: productCategories
        joinColumn:
          name: product_id
          referencedColumnName: id