<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \AppBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'order_code', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'origin_price', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'sale_price', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'quantity', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'transfer_fee', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'total_money', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'total_profit', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'fullname', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'phone', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'note', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'customer_id', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'product_id', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'order_desc', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'cancel_reason', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'created_at', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'updated_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'order_code', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'origin_price', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'sale_price', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'quantity', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'transfer_fee', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'total_money', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'total_profit', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'fullname', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'phone', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'note', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'customer_id', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'product_id', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'order_desc', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'cancel_reason', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'created_at', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'updated_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderCode($orderCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderCode', [$orderCode]);

        return parent::setOrderCode($orderCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderCode', []);

        return parent::getOrderCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginPrice($originPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginPrice', [$originPrice]);

        return parent::setOriginPrice($originPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginPrice', []);

        return parent::getOriginPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalePrice($salePrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalePrice', [$salePrice]);

        return parent::setSalePrice($salePrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalePrice', []);

        return parent::getSalePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', [$quantity]);

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', []);

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransferFee($transferFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransferFee', [$transferFee]);

        return parent::setTransferFee($transferFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransferFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransferFee', []);

        return parent::getTransferFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalMoney($totalMoney)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalMoney', [$totalMoney]);

        return parent::setTotalMoney($totalMoney);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalMoney', []);

        return parent::getTotalMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalProfit($totalProfit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalProfit', [$totalProfit]);

        return parent::setTotalProfit($totalProfit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalProfit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalProfit', []);

        return parent::getTotalProfit();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullname($fullname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullname', [$fullname]);

        return parent::setFullname($fullname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullname', []);

        return parent::getFullname();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId($customerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', [$customerId]);

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', []);

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductId($productId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductId', [$productId]);

        return parent::setProductId($productId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', []);

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderDesc($orderDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderDesc', [$orderDesc]);

        return parent::setOrderDesc($orderDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDesc', []);

        return parent::getOrderDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelReason($cancelReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelReason', [$cancelReason]);

        return parent::setCancelReason($cancelReason);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelReason', []);

        return parent::getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

}
