<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Color extends \AppBundle\Entity\Color implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'hex_code', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'icon_path', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'products', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'productColors', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'pColors'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'hex_code', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'icon_path', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'products', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'productColors', '' . "\0" . 'AppBundle\\Entity\\Color' . "\0" . 'pColors'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Color $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHexCode($hexCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHexCode', [$hexCode]);

        return parent::setHexCode($hexCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getHexCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHexCode', []);

        return parent::getHexCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setIconPath($iconPath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIconPath', [$iconPath]);

        return parent::setIconPath($iconPath);
    }

    /**
     * {@inheritDoc}
     */
    public function getIconPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIconPath', []);

        return parent::getIconPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\AppBundle\Entity\Product $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', [$product]);

        return parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\AppBundle\Entity\Product $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', [$product]);

        return parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', []);

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductColor(\AppBundle\Entity\ProductColor $productColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductColor', [$productColor]);

        return parent::addProductColor($productColor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductColor(\AppBundle\Entity\ProductColor $productColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductColor', [$productColor]);

        return parent::removeProductColor($productColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductColors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductColors', []);

        return parent::getProductColors();
    }

    /**
     * {@inheritDoc}
     */
    public function addPColor(\AppBundle\Entity\ProductColor $pColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPColor', [$pColor]);

        return parent::addPColor($pColor);
    }

    /**
     * {@inheritDoc}
     */
    public function removePColor(\AppBundle\Entity\ProductColor $pColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePColor', [$pColor]);

        return parent::removePColor($pColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPColors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPColors', []);

        return parent::getPColors();
    }

}
